### ISSUE TITLE
parametrize minio and influxDB to allow setting storageclass

### ISSUE THREAD

**Issue by gioppoluca** [ddosify/ddosify-helm-charts#1]
Is not possible to configure the minio and influxdb storageclass, please add the option to set in in values

**Comment by fatihbaltaci** [comment]
Hello @gioppoluca, Thank you for raising this issue.

To better understand your requirements, could you kindly provide us with your use cases for changing the storage class? 

We would be happy to add this feature to our helm chart  along with this issue: https://github.com/ddosify/ddosify-helm-charts/issues/2

**Comment by fatihbaltaci** [comment]
Hi @gioppoluca, Ddosify chart 1.3.0 is ready on GitHub. You can upgrade Ddosify using [these](https://github.com/ddosify/ddosify-helm-charts#upgrading-the-ddosify-chart) instructions.

You can set storage class for postgres, influxDB and seaweedfs now. You can override the values.yaml file: https://github.com/ddosify/ddosify-helm-charts/blob/7f6234e215ae80a648103025039ee82f92901d6d/ddosify/values.yaml#L103

If you have any questions, please let me know.

**Comment by gioppoluca** [comment]
tested and it works
