### ISSUE TITLE
[Feature Request:] Add option to set resource/requests and annotations/labels

### ISSUE THREAD

**Issue by GeiserX** [ddosify/ddosify-helm-charts#7]
I am currently trying to deploy Alaz on my cluster, but it's failing in one of the nodes because of insufficient CPU. I'd like to be able to tinker with requests/limits by myself in the `values.yaml` file, instead of having to modify manually the DaemonSet within the cluster.

I'd like to see as well the option to add annotations/labels as well.

It's good practice to let the user decide as well on the repo/image/more stuff...

**Comment by fatihbaltaci** [comment]
Hello @GeiserX, now you can set the resource limits and resources in the [last release of Alaz](https://github.com/ddosify/ddosify-helm-charts/releases/tag/alaz-0.2.1). 

Annotations, labels, and other parameters are parameterized in [values.yaml](https://github.com/ddosify/ddosify-helm-charts/blob/master/charts/alaz/values.yaml) file. 

Thanks.

**Comment by GeiserX** [comment]
Thank you, closing issue
